### PR TITLE
Add Head prototype and add change handling

### PR DESCRIPTION
**Pull request by Aichnerc**
You can now edit the head and locally save the changes.

**Checklist:**

 
 - [x] Have you added an explanation of what your changes do and why you'd like them to be included?
 - [ ] Have you updated or added documentation for the change?
 - [x] Have you tested your changes with successful results?

**Type of Changes:**

 
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] New feature (non-breaking change which adds functionality)
 - [x] Documentation (non-breaking change which adds documentation)
 - [x] Breaking change (fix or feature that would cause existing functionality to change)

**What is the current behavior? (link to any open issues here)**
- Currently it is not possible to change a given text.

**What is the new behavior (if this is a feature change)?**
- It is now possible to edit a text and receive data of the position and new text.

### CODE REVIEW

**Review by LucaAllmaier — APPROVED** [review]
Looks good to me.

**Review by sweggerat — APPROVED** [review]
looks good

**Review by kleberbaum — APPROVED** [review]
Should be ok to merge.

**Review by ginanet — APPROVED** [review]
LGTM

**Review by schettn — APPROVED** [review]
LGTM!

**Pull request merged**
